#!/bin/sh
#
# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2020 Marvell
#
# Script to setup interfaces used for running application on linux-generic.
#
# For linux-generic the default behavior is to create two pcap interfaces
# and one interface uses udp64.pcap to inject traffic. An output pcap file
# is generated via second interface.
#
# Network set-up
# IF0 <---> IF1

PCAP_IN=`find . ${TEST_DIR} $(dirname $0) -name udp64.pcap -print -quit`
echo "using PCAP_IN = ${PCAP_IN}"

IF0=pcap:in=${PCAP_IN}
IF1=pcap:out=pcapout.pcap

if [ "$0" = "$BASH_SOURCE" ]; then
	echo "Error: Platform specific env file has to be sourced."
fi

validate_result()
{
	if [ `stat -c %s pcapout.pcap` -ne `stat -c %s  ${PCAP_IN}` ]; then
		echo "File sizes disagree"
		exit 1
	fi

	rm -f pcapout.pcap
}

setup_interfaces()
{
	echo "pktio: setting up test interfaces $IF0, $IF1."
	return 0
}

cleanup_interfaces()
{
	echo "pktio: cleaning up test interfaces $IF0, $IF1."
	return 0
}
