language: c

compiler:
  - gcc
  - clang

env:
    - CONF="--disable-test-perf"
    - CONF="--disable-abi-compat --disable-test-perf"
    # - CONF="--enable-schedule-sp"
    # - CONF="--enable-schedule-iquery"
    # - CONF="--enable-dpdk-zero-copy"
    # - CROSS_ARCH="arm64"
    # - CROSS_ARCH="armhf" CFLAGS="-march=armv7-a"
    # - CROSS_ARCH="powerpc"
    # - CROSS_ARCH="i386"

matrix:
  allow_failures:
    - compiler: clang
      env: CONF="--disable-abi-compat --disable-test-perf"

build:
  pre_ci:
    # use Dockerfile to install additional CI dependencies
    - docker build -t=odp/dev ./scripts

  # use image built in 'pre_ci' for CI job
  pre_ci_boot:
    image_name: odp/dev
    image_tag: latest
    pull: false
    options:

  ci:
    - echo 1000 | sudo tee /proc/sys/vm/nr_hugepages
    - sudo mkdir -p /mnt/huge
    - sudo mount -t hugetlbfs nodev /mnt/huge
    - mkdir -p /dev/shm/odp
    - ./bootstrap
    - if [ "${CC#clang}" != "${CC}" ] ; then export CXX="${CC/clang/clang++}"; fi
    - ./configure $CONF
    - make -j $(nproc)
    - sudo env ODP_SHM_DIR=/dev/shm/odp ODP_TEST_OUT_XML=yes make check -k

  on_success:
    - ./scripts/shippable-post.sh

  on_failure:
    - ./scripts/shippable-post.sh
    - cat config.log
    - find . -name "*.trs" | xargs grep -l '^.test-result. FAIL' | while read trs ; do echo FAILURE detected at $trs; cat ${trs%%.trs}.log ; done
