#!/bin/sh
#
# Script that passes command line arguments to odp_scheduling test when
# launched by 'make check'

ret=0

run()
{
	echo odp_scheduling_run starts with $1 worker threads
	echo ===============================================

	./odp_scheduling -c $1 || ret=1
}

run 1
run 8

exit $ret
