#!/bin/sh
#
# Copyright (C) 2020, Marvell
# All rights reserved.
#
# SPDX-License-Identifier:	BSD-3-Clause
#
# Script to setup interfaces used for running application on linux-generic.
#
# Generator uses null interfaces to validate udp mode.
#
# Network set-up
# IF0 ---> null:0

IF0=null:0

if [ "$0" = "$BASH_SOURCE" ]; then
	echo "Error: Platform specific env file has to be sourced."
fi

validate_result()
{
	return 0
}

setup_interfaces()
{
	return 0
}

cleanup_interfaces()
{
	return 0
}
