#!/bin/bash

set -e

ROOT_DIR=$(readlink -e $(dirname $0) | sed 's|/scripts||')
version=$(${ROOT_DIR}/scripts/odp_version.sh)

pushd ${ROOT_DIR}
./bootstrap
./configure
make dist

cp opendataplane-${version}.tar.gz opendataplane_${version}.orig.tar.gz
tar xzf opendataplane_${version}.orig.tar.gz

pushd ${ROOT_DIR}/opendataplane-${version}
cp -r ${ROOT_DIR}/debian .

current=$(echo ${version} | awk -F . '{printf("%d\n", (($1 * 100) + $2))}')
rename 's,([^-\.]*)(.*),${1}'"${current}"'${2},' debian/*odp*

sed -i "s:\(.*odp\)\([^\.]\|$\):\1${current}\2:g" debian/control
sed -i "s:\(.*odp\)\(.*\):\1${current}\2:g" debian/rules

debuild -us -uc
popd
popd
