#!/bin/sh
#
# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2016-2018 Linaro Limited
#

PATH=$(dirname $0):$PATH
PATH=.:$PATH

# The odpthreads test without the "--odph_proc" option defaults to create
# odp threads as linux pthreads:
odpthreads${EXEEXT}
