#!/bin/sh
#
# Copyright (c) 2016, Linaro Limited
# All rights reserved.
#
# SPDX-License-Identifier:	BSD-3-Clause
#

PATH=$(dirname $0):$PATH
PATH=.:$PATH

# The odpthreads test without the "--odph_proc" option defaults to create
# odp threads as linux pthreads:
odpthreads
