#!/bin/sh
#
# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2016-2018 Linaro Limited
#

PATH=$(dirname $0):$PATH
PATH=.:$PATH

# The odpthreads test recognise the "--odph_proc" option to create
# odp threads as linux processes:
odpthreads${EXEEXT} --odph_proc
